version: '3'
services:
  todo-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-server
    container_name: "todo-server"
    ports:
      - 8080:8080
    links:
      - todo-database:database
    depends_on:
      - todo-database

  todo-database:
    restart: always
    image: postgres:10.10
    container_name: "todo-database"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "todo-root"
      POSTGRES_PASSWORD: "todo-root"
      POSTGRES_DB: "todo"



