server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/todo
    username: todo-root
    password: todo-root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: beans
